### PR TITLE
also count aws-sdk operations

### PR DESCRIPTION
**Pull request by jhford**
Can we also count these operations?  Almost more than the duration right now, what I need is the count.  I'm also going to probably ask for more things to add.  Not sure how this should impact semver...

### CODE REVIEW

**Comment by jhford** [comment]
I'd also _really_ love it if we could do both of these metrics by region!

**Comment by jhford** [comment]
Random question: can prefixed monitors patchAWS?  If I have sqs _and_ s3 with one monitor, can I patch both?  So far, it seems like no

```
TypeError: m.patchAWS is not a function
```

``` javascript
      let m = monitor.prefix('sqs');
      m.patchAWS(sqs);
```

**Comment by imbstack** [comment]
What's in here now seems reasonable. r+

I'll leave this open so we can add whatever else we want now as well.

Adding regions sounds fine as well. It will increase the amount of metrics stored but not by a huge amount as it's just a single new dimension and not a cross-product explosion.

I'm pretty sure that as it stands you can't monitor from a prefix. I don't think I see a reason why that _should_ be that way. I think it was just an arbitrary decision before.

**Comment by jhford** [comment]
cool!  I guess in the `patchAWS` there's some way to determine which service that we're in?  what I really want is a way to know hypothetical operation X came from an EC2 client or SQS client.

Just having ec2.describeSpotInstanceRequests rather than just describeSpotInstanceRequests would be perfect.  I'll look into how this works.

**Comment by jhford** [comment]
Aha, my concern about the prefix'd thing not working is unneeded, I looked at the code and the patchAWS method does internally prefix with the service name.

**Comment by jhford** [comment]
@imbstack I think this is all I'm looking for here.  Adding the `.global.` string is a way to make wildcard searching a little easier... i think...  I don't have a great answer to making wildcard matching pleasant with lib-monitor prefixes.

**Comment by jhford** [comment]
We could also include nice things like `statusCode` and `retryCount` from the response object, but I'm not certain that we need that right now.

https://github.com/aws/aws-sdk-js/blob/a737d93a82b4d58425fb0e3d749739b952950786/lib/event_listeners.js#L414

**Comment by jhford** [comment]
Not sure why, but locally I cannot get these tests to pass.

```
  33 passing (3s)
  1 pending
  2 failing

  1) Uncaught Errors should report uncaught exceptions:

      AssertionError: false == true
      + expected - actual

      -false
      +true

      at ChildProcess.<anonymous> (test/uncaught_test.js:70:9)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)

  2) Uncaught Errors should exit no matter what:

      AssertionError: false == true
      + expected - actual

      -false
      +true

      at ChildProcess.<anonymous> (test/uncaught_test.js:111:9)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
```

**Comment by imbstack** [comment]
Those are definitely hacky tests, so I wouldn't be surprised if it's hard to get them to pass.

**Pull request merged**
