### PR TITLE
Swap out Firehose support for Kinesis

### PR DESCRIPTION
**Pull request by ajvb**
Use Kinesis API in auditlog (through `KinesisLog`) instead of Firehose.

bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1488556

r? @imbstack

### CODE REVIEW

**Review by imbstack — APPROVED** [review]
Awesome. I'll try to terraform up a stream soon and then we can try deploying this.

**Comment by ajvb** [comment]
Ok, I think I actually did this wrong. We will want to use [`kinesis.putRecords`](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Kinesis.html#putRecords-property) instead of the `kinesis.putRecord` call, where each `Record` is a single log line.

**Comment by ajvb** [comment]
I think it should be something like this:

```javascript
let krecords = records.map(line => {
  return {Data: line.line, PartitionKey: AUDITLOG_PARTITION_KEY};
});

res = await this._kinesis.putRecords({
  StreamName: this._logName,
  Records: krecords,
}).promise();
```

**Comment by imbstack** [comment]
Just tried this in staging and it works!

**Comment by imbstack** [comment]
The staging cluster is being used this whole week for some testing and we're not ready quite yet to set up a second staging cluster so maybe we'll just land this without a second trip through staging. I can set up the terraform for prod tomorrow.

**Comment by ajvb** [comment]
@imbstack :+1:

**Pull request merged**
