### PR TITLE
Use different strategy for logs which reduces cost

### PR DESCRIPTION
**Pull request by imbstack**
The cost we calculated for this for auth audit logging was bothering me. It just seemed too high (~ $100/month).

This new strategy should reduce the cost to ~$10/month. The munging together of records is actually what ends up happening in firehose anyway. This both saves us money and makes the code simpler.

### CODE REVIEW

**Comment by imbstack** [comment]
Once we're happy with this, if you look over taskcluster/taskcluster-auth#102 again, I think we can ship it all.

**Review by djmitche — COMMENTED** [review]
Can you describe the difference?  It's not clear, at least since I don't know much about Kinesis.

**Comment by imbstack** [comment]
The only real difference here is using `putRecord` instead of `putRecordBatch`. Kinesis Firehose charges by bytes/month. However, each "record" is rounded up to 5KB. Our records are about 350 bytes each on average. This inflated our cost by 5000/350 times. On their end, all they were doing with each record anyway was munging them together and sticking it in s3. We're just doing the munging on our side now. If/when we decide to do something other than s3, we might have to change this back, but since that's not known for now, I figured we can save some money.

**Comment by djmitche** [comment]
I see, so this is combining multiple records into one concatenated record.  Is the `.join('')` intentional, or should that be a newline

**Comment by imbstack** [comment]
Intentional since each line already has a `\n` appended. We can also not do this if the cost savings aren't worth it!

**Review by djmitche — APPROVED** [review]
No, I think it's worth it, just making sure I understand :)

**Pull request merged**
